In [5]:
stack = ["ROOT", "the", "cat"]
stack = stack[0:-2] + [stack[-1]]
print("stack = ", stack)

stack =  ['ROOT', 'cat']


In [8]:
stack = ["ROOT", "the"]
stack[0:-2] + [stack[-1]]

['the']

In [9]:
import torch
import torch.nn as nn

# Import pprint, module we use for making our print statements prettier
import pprint
pp = pprint.PrettyPrinter()



A module that was compiled using NumPy 1.x cannot be run in
NumPy 2.0.0 as it may crash. To support both 1.x and 2.x
versions of NumPy, modules must be compiled with NumPy 2.0.
Some module may need to rebuild instead e.g. with 'pybind11>=2.12'.

If you are a user of the module, the easiest solution will be to
downgrade to 'numpy<2' or try to upgrade the affected module.
We expect that some modules will need time to support NumPy 2.

Traceback (most recent call last):  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "/Users/Paul/opt/anaconda3/envs/cs224n_a2/lib/python3.12/site-packages/ipykernel_launcher.py", line 18, in <module>
    app.launch_new_instance()
  File "/Users/Paul/opt/anaconda3/envs/cs224n_a2/lib/python3.12/site-packages/traitlets/config/application.py", line 1075, in launch_instance
    app.start()
  File "/Users/Paul/opt/anaconda3/envs/cs224n_a2/lib/python3.12/site-packages/ipykernel/kernelapp.py", line 739,

In [ ]:
w = [
    [0, 2, 3],
    [0, 1, 2]
]

e = [
    [1, 11, 111, 1111, 11111],
    [2, 22, 222, 2222, 22222],
    [3, 33, 333, 3333, 33333],
    [4, 44, 444, 4444, 44444]
]
torch.index_select(self.embeddings, 0, w)

In [17]:
words = ["a", "the", "zebra", "a", "the"]
word2ind = {}
for i, w in enumerate(words):
    word2ind[w] = i
    
pp.pprint(word2ind)


{'a': 3, 'the': 4, 'zebra': 2}


In [16]:
for i in range(0,0):
    print(i)

In [19]:
def distinct_words(corpus):
    """ Determine a list of distinct words for the corpus.
        Params:
            corpus (list of list of strings): corpus of documents
        Return:
            corpus_words (list of strings): sorted list of distinct words across the corpus
            n_corpus_words (integer): number of distinct words across the corpus
    """
    corpus_words = []
    n_corpus_words = -1

    # ------------------
    # Write your implementation here.

    corpus_words = sorted(list(set([w for doc in corpus for w in doc])))
    n_corpus_words = len(corpus_words)

    # ------------------

    return corpus_words, n_corpus_words

In [20]:
corpus = [
    ["the", "cat", "in", "the", "hat", "sat", "on", "the", "mat"],
    ["the", "cat", "slept", "peacefully"]
]
words, n_words = distinct_words(corpus)
print("words = ", words)
print("n_words = ", n_words)
M = None
word2ind = {}


words =  ['cat', 'hat', 'in', 'mat', 'on', 'peacefully', 'sat', 'slept', 'the']
n_words =  9


In [22]:
import numpy as np

In [25]:
M = np.zeros((n_words, n_words))
for i, w in enumerate(words):
    word2ind[w] = i

print("word2ind = ", word2ind)
print("M = ", M)
    

word2ind =  {'cat': 0, 'hat': 1, 'in': 2, 'mat': 3, 'on': 4, 'peacefully': 5, 'sat': 6, 'slept': 7, 'the': 8}
M =  [[0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0.]]
